### ISSUE TITLE
damage taken not displayed in default channel

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#11]
example: 
13:37 You lose 123 hitpoint due to an attack by a monster/player.

**Comment by babymannen** [comment]
Fixed. Thanks.

**Comment by Seliro** [comment]
it is not fixed 
![notfixed](http://i.imgur.com/Q5exUzN.jpg)

example of what i mean, look in default chat when the player takes damage
https://www.youtube.com/watch?v=Se4dYs3XfWc&t=23m02s

**Comment by Seliro** [comment]
@babymannen, @peonso, not sure how i reopen this issue so il just tag you

**Comment by babymannen** [comment]
Wops. Should be fixed now.

**Comment by Seliro** [comment]
![tested](http://i.imgur.com/cjySt0K.png)

**Comment by Seliro** [comment]
02:18 Sorcerer two loses 164 hitpoints due to your attack.
02:18 Sorcerer two loses 164 hitpoints due to an attack by Sorcerer.

these two should get removed

**Comment by Seliro** [comment]
also
![asd](http://www.tibia.pl/drom/img/refugia/elvesraid1.jpg)

currently:
06:13 You lose 3 mana due to an attack by an elf scout.

should be:
06:13 You lose 3 mana blocking an attack by an elf scout.

i'm guessing the default chat should also say something like that
